MySolution/Models/Country.cs
using System;
using System.Xml.Serialization;

namespace MySolution.Models
{
    /// <summary>
    /// Represend a model of country. 
    /// </summary>
    [Serializable]
    [XmlRoot("country")]
    public class Country
    {
        /// <summary>
        /// Get or set a primary key value
        /// </summary>
        [XmlAttribute("id")] 
        public Guid Id { get; set; }
        /// <summary>
        /// Get or set a country name value.
        /// </summary>
        [XmlElement("name")]
        public string Name { get; set; }
        /// <summary>
        /// Get or set capital name value.
        /// </summary>
        [XmlElement("capital")]
        public string Capital { get; set; }
        /// <summary>
        /// Get or set description abaut a country. 
        /// </summary>
        [XmlElement("description")] public string Description { get; set; }

    }
}

MySolution/Controllers/CountryController.cs
using MySolution.Abstraction;
using MySolution.Implementations;
using MySolution.Models;
using MySolution.Properties;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Xml.Linq;

namespace MySolution.Controllers
{
    public class CountryController : Controller
    {
        private readonly IRepository<Country, Guid> _repository;
        public CountryController()
        {
            _repository = DependencyResolver.Current.GetService<XmlCountryRepository>();
            
        }
        
        public ActionResult Index()
        {
            _repository.CreateConnection(HttpContext.Server.MapPath(Settings.Default.StoragePathAndName));
            var countries = _repository.GetAll();
            if (countries == null && _repository.ExceptionAnOperation != null) throw  _repository.ExceptionAnOperation;
            return View(countries);
        }
        [HttpPost]
        public ActionResult SaveCountry(Country model)
        {
            if (model == null) return View("Error");
            _repository.CreateConnection(HttpContext.Server.MapPath(Settings.Default.StoragePathAndName));
            if (model.Id == Guid.Empty && !string.IsNullOrEmpty(model.Name))
            {
                if (_repository.Add(model) == null || !_repository.CommitChanges()) throw _repository.ExceptionAnOperation;
            }
            else if (model.Id != Guid.Empty && !string.IsNullOrEmpty(model.Name))
            {
                if (_repository.Update(model) == null || !_repository.CommitChanges()) throw _repository.ExceptionAnOperation;
            }
            else
            {
                return View("Error");
            }
            return RedirectToAction("Index");
        }
        public ActionResult CreateCountry()
        {
            ViewBag.Title = "Add new country";
            return PartialView("_AddAndEditForm", new Country());
        }
        public ActionResult EditCountry(Guid? id)
        {
            if (id==null|| id == Guid.Empty) return View("Error");
            _repository.CreateConnection(HttpContext.Server.MapPath(Settings.Default.StoragePathAndName));
            var coutry = _repository.Find(id.Value);
            if (coutry==null) return View("Error");
            ViewBag.Title = "Edit the country";
            return PartialView("_AddAndEditForm", coutry);
        }
        public ActionResult DeleteCountry(Guid? id)
        {
            if (id==null || id == Guid.Empty) return View("Error");
            _repository.CreateConnection(HttpContext.Server.MapPath(Settings.Default.StoragePathAndName));
            if (!_repository.Delete(id.Value) || !_repository.CommitChanges()) throw _repository.ExceptionAnOperation;
            return RedirectToAction("Index");

        }
        public ActionResult DetailsCountry(Guid? id)
        {
            if (id == null || id == Guid.Empty) return View("Error");
            _repository.CreateConnection(HttpContext.Server.MapPath(Settings.Default.StoragePathAndName));
            var coutry = _repository.Find(id.Value);
            if (coutry == null) return View("Error");
            return PartialView("_ShowDetails", coutry);
        }
    }
}

MySolution/Views/Country/Index.cshtml
@model IEnumerable<MySolution.Models.Country>

@{
    ViewBag.Title = "Countries";
    var coun = Model.ToList<MySolution.Models.Country>();
}
<div id="content">
    <h3>
        List of countries  @Html.ActionLink("New", "CreateCountry", new { }, new { @class = "btn btn-success", @type = "button" })
    </h3>
    <div id="list-of-country">
        <table class="table table-hover table-bordered ">
            <thead>
                <tr>
                    <td>#</td>
                    <td>Name</td>
                    <td>Capital</td>

                    <td></td>
                </tr>
            </thead>
            <tbody>
                @{
                    for (int i = 0; i < coun.Count; i++)
                    {
                        <tr>
                            <td>@i</td>
                            <td>@coun[i].Name</td>
                            <td>@coun[i].Capital</td>
                            <td >
                                <div class="btn-group" role="group" aria-label="...">
                                    @Html.ActionLink("Edit", "EditCountry", new { id = coun[i].Id }, new { @class = "btn btn-default btn-xs", @type = "button" })
                                    @Html.ActionLink("Delete", "DeleteCountry", new { id = coun[i].Id }, new { @class = "btn btn-danger btn-xs", @type = "button" })
                                    @Html.ActionLink("Detail", "DetailsCountry", new { id = coun[i].Id }, new { @class = "btn btn-info btn-xs", @type = "button" })
                                </div>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>

MySolution/Views/Country/_AddAndEditForm.cshtml
@model MySolution.Models.Country
@{Layout = "~/Views/Shared/_Layout.cshtml";}

@using (Html.BeginForm("SaveCountry", "Country", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@ViewBag.Title</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Capital, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Capital, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Capital, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MySolution/Views/Country/_ShowDetails.cshtml
@model MySolution.Models.Country
@{Layout = "~/Views/Shared/_Layout.cshtml";}
<div>
    <h3>Details:</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Capital)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Capital)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "EditCountry", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MySolution/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Countries</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Country storage", "Index", "Country", new { area = "" }, new { @class = "navbar-brand" })
            </div>
      </div>
    </div>
    <div class="container body-content">
        <br />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Solution was made by Ihor Rachkovskyi</p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>